if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
  set(BNG_IS_WINDOWS TRUE)
  set(BNG_PLATFORM "windows")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  set(BNG_IS_MACOS TRUE)
  set(BNG_PLATFORM "macos")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(BNG_IS_LINUX TRUE)
  set(BNG_PLATFORM "linux")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
  set(BNG_IS_ANDROID TRUE)
  set(BNG_PLATFORM "android")
elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
  set(BNG_IS_IOS TRUE)
  set(BNG_PLATFORM "ios")
else()
  message(FATAL_ERROR "Unsupported platform ${CMAKE_SYSTEM_NAME}")
endif()
